version: 0.1.{build}
image: Visual Studio 2017
environment:
  COVERALLS_REPO_TOKEN:
    secure: zQ/VgsxygmWndVF6mUoHkYNk8rux01mgQt/p/OJvIdAp3X+FfJUrP3HcG6rbpqJM
build_script:
- cmd: >-
    dotnet restore

    dotnet build
test_script:
- ps: .\coveralls.ps1
deploy: off