version: 0.1.{build}
image: Visual Studio 2017
environment:
  COVERALLS_REPO_TOKEN:
    secure: k+0InS2aLYQUK9lnSuMiMptDMQWgn4RF3skssvH4L4EdM10IbUfM448UB69CAb+qmbLlbL+/TovSng5XsPsGQc76D/JduJC1KVSOxuU4u5Q=
build_script:
- cmd: >-
    dotnet restore

    dotnet build
test_script:
- ps: .\coveralls.ps1
deploy: off