version: 0.1.{build}
image: Visual Studio 2017
environment:
  COVERALLS_REPO_TOKEN:
    secure: +VA483EEFhCFwcB9Bv9I2O2MlloRP45C+pJ44RAEMPmSE1GzcI3K/egDbcJTWQ6pEQFfyXYG6GrNFJclIOgkiBwWWtJ027ujmpdEE6nSz5g=
build_script:
- cmd: >-
    dotnet restore

    dotnet build
test_script:
- ps: .\coveralls.ps1
deploy: off